import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';

export interface ImageVariants {
  thumbnail?: string; // 256px width WebP
  small?: string; // 512px width WebP
  medium?: string; // 768px width WebP
  large?: string; // 1536px width WebP
}

export interface ImageDimensions {
  original?: { width: number; height: number };
  thumbnail?: { width: number; height: number };
  small?: { width: number; height: number };
  medium?: { width: number; height: number };
  large?: { width: number; height: number };
}

@Entity('files')
export class File {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  s3Key: string;

  @Column()
  @Index()
  type: string;

  /**
   * Image variants generated by Sharp (WebP format)
   * Contains URLs for thumbnail, medium, and large sizes
   */
  @Column({ type: 'jsonb', nullable: true })
  variants?: ImageVariants;

  /**
   * Dimensions for each image variant
   * Used for CLS prevention in frontend
   */
  @Column({ type: 'jsonb', nullable: true })
  dimensions?: ImageDimensions;

  /**
   * Flag indicating if Sharp processing has completed
   * Used to determine if Cloudflare transforms should be used as fallback
   */
  @Column({ type: 'boolean', default: false })
  @Index()
  isProcessed: boolean;

  /**
   * Error message if processing failed
   * Allows for debugging and retry logic
   */
  @Column({ type: 'text', nullable: true })
  processingError?: string;

  @CreateDateColumn()
  @Index()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
